include:
  - infra.yaml

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-dev
    env_file:
      - .env
    ports:
      - ${DEV_PORT}:8000
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    networks:
      - rag-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 30s
      interval: 10s
      retries: 5
      timeout: 10s
    depends_on:
    #   redis:
    #     condition: service_healthy
      postgres:
        condition: service_healthy
    #   qdrant:
    #     condition: service_healthy

networks:
  rag-net:
    name: rag-net
