include:
  - infra.yaml

services:
  app:
    image: f00hy/rag-app:main
    container_name: rag-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    networks:
      - rag-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      start_period: 30s
      interval: 10s
      retries: 5
      timeout: 10s
    # depends_on:
    #   redis:
    #     condition: service_healthy
    #   postgres:
    #     condition: service_healthy
    #   qdrant:
    #     condition: service_healthy

networks:
  rag-net:
