# Reference: https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile

FROM ghcr.io/astral-sh/uv:0.9-python3.12-trixie-slim

RUN groupadd --system --gid 999 nonroot \
 && useradd --system --gid 999 --uid 999 --create-home nonroot

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_NO_DEFAULT_GROUPS=true
ENV UV_PYTHON_DOWNLOADS=0
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --group dev --no-install-project

COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --group dev

ENV PATH=/app/.venv/bin:$PATH
ENV FASTEMBED_CACHE_PATH=/app/.cache/fastembed
ENV HF_HOME=/app/.cache/huggingface

RUN python -c "\
from fastembed import TextEmbedding, SparseTextEmbedding;\
from fastembed.rerank.cross_encoder import TextCrossEncoder;\
from tokenizers import Tokenizer;\
TextEmbedding('BAAI/bge-base-en-v1.5');\
SparseTextEmbedding('prithivida/Splade_PP_en_v1');\
TextCrossEncoder('jinaai/jina-reranker-v1-turbo-en');\
Tokenizer.from_pretrained('prithivida/Splade_PP_en_v1')"

ENTRYPOINT []

USER nonroot

EXPOSE 8000

CMD ["fastapi", "dev", "--host", "0.0.0.0", "--port", "8000", "app/main.py"]
