# Git
.git
.gitignore

# Python
__pycache__
.venv
.python-version

# Ruff
.ruff_cache

# Docker
Dockerfile
Dockerfile.dev
compose.yaml
compose.dev.yaml
infra.yaml
.dockerignore

# Database Migrations
alembic

# GitHub
.github

# Pre-commit
.pre-commit-config.yaml

# Scripts
scripts

# Tests
.pytest_cache
.deepeval

# Environment
.env
.env.example
